### ISSUE TITLE
ImportError: cannot import name '_C' from 'kaolin' 

### ISSUE THREAD

**Issue by psx2** [postech-ami/CLIP-Actor#1]
Hi there,

I have followed the instructions exactly as provided, and when testing the example prompt you provided, I am greeted with this:

![519](https://user-images.githubusercontent.com/77219161/179967134-f2e87c88-de71-47cb-8227-8143703e4d54.png)

Any thoughts?

**Comment by psx2** [comment]
I've also tried your instructions on a fresh AWS Linux server, and was unable to run. Can you please confirm that everything is correct, and you have tested?

**Comment by Youwang-Kim** [comment]
I have tested before and again about the environment setting and I got everything working. 

Your error seems like the library (kaolin) are not installed properly. 
Can you check your kaolin's installation log? I suspect it failed during installation. 
Please check your pytorch version, which is critical for the kaolin's operation.

Or maybe you can [install kaolin v0.9.1 manually](https://kaolin.readthedocs.io/en/latest/notes/installation.html) (not from pip install -r requirements.txt)
You may want to check [this issue](https://github.com/NVIDIAGameWorks/kaolin/issues/503).

If all above are not working, can you please check your system's configuration? 
This code was developed on Ubuntu 18.04 with Python 3.7, CUDA 10.2 and PyTorch 1.9.0. 

Please let me know if you have further problems 🙏

**Comment by Caenorst** [comment]
Hi there, we do not recommend to `pip install` Kaolin as it may not work on some systems (typically windows). As @Youwang-Kim recommended please try to install from source.
