### ISSUE TITLE
about the demo performence

### ISSUE THREAD

**Issue by lai-pf** [postech-ami/CLIP-Actor#4]
I tried the demo "Freddie Mercury dancing"  using a tesla P40(24G)GPU
And I got Freddire results like this
![image](https://user-images.githubusercontent.com/32856760/194788574-96659856-5d43-4a03-baa5-c8b252bad8c1.png)
But in paper , It looks like this
![image](https://user-images.githubusercontent.com/32856760/194788622-0762bec9-e7ef-4ffa-923f-6e3de8be2df0.png)
Can you tell me how to reproduce the example results in paper? 
Thanks for sharing the project and your help.

**Comment by Youwang-Kim** [comment]
Hi, thank you for your interest, and sorry for the late delay. 
All the textures could be generated randomly, depend on which machine you use and which seed you are using. 
We are currently working on the improved version of CLIP-Actor, so please stay tuned for the better results!
