### ISSUE TITLE
How to make a A-pose model for comparison

### ISSUE THREAD

**Issue by zeng-yifei** [postech-ami/CLIP-Actor#5]
I have tried to using a prompt like "Obama is standing", but can't produce a reasonable standing pose obj like A-pose.

How could I create a model that only stands and doing nothing?

**Comment by Youwang-Kim** [comment]
Hi, thank you for the interest in our project. 

Regarding the A-pose (or T-pose), you could just dump the retrieved motion with zeroes:
https://github.com/postech-ami/CLIP-Actor/blob/c1b3f1a0a6d5ea75f03ee58807ff0abfd965ab13/clip_actor.py#L415

For example, you can do it like below
```
body_pose, right_hand_pose, left_hand_pose = torch.zeros_like(body_pose, device=device), torch.zeros_like(right_hand_pose, device=device), torch.zeros_like(left_hand_pose, device=device)
```

Hope this helps.

**Comment by Youwang-Kim** [comment]
Please reopen this issue if you need more help regarding this.

**Comment by zeng-yifei** [comment]
I didn't expect such a quick reply. :-)

Thank you very much! It works finally!
